#!/usr/bin/env python3

#import funtions
import serial 
import time
import rospy
import sys
import os

from std_msgs.mgs import Int32MultiArray

bo = [0, 0, 0, 0, 0, 0]

#Define serial communication
#This is a test case to make sure that the serial communication is working properly
ser = serial.Serial('/dev/ttyACM0', 115200, timeout = 1)
ser.reset_input_buffer()

#This is the fucntion that will send the array to the Arduino MEGA
def send_array(numbers):
#Convert the list into a string
data_str = ','.join(map(str, numbers))

#Send the Encoded array to the Arduino
#Has a case to test if the message was sent properly
try:
ser.write(data_str.encode('utf-8'))
ser.write(b"\n") #Newline the signal data end
rospy.logininfo(f"Sent array over serial: {data_str}")
except Exception as e:
rospy.logerr(f"Error sending data over serial: {e}")

#Call abck function (Happens when the publisher node recieves an message)
def callback(data):
numbers = list(data.data)

#while waiting for the next message it will print out what the Arduino has received
while ser.in_waiting > 0:
line = ser.readline().decode('utf-8').rstrip()
rospy.loginfo(f"Arduino says: {line}")
        
        if line.startswith("Flysky:"):
            values = line.split(":")[1].split(",")
            start = bool(int(values[0]))
            shut = bool(int(values[1]))
            
            rospy.logininfo(f"Flysky - start {start}, E-stop: {shut}")
            
            if start == 1:
                numbers = numbers + [1,1]
                send_array(numbers)
            else:
                send_array(bo)
                
            if shut == 1:
                send_array(bo)
                os.system("shutdown -h now")

def number_array_subscriber():
#Initialize the ros node
rospy.init_node('number_array_subscriber', anonymous=True)

#Create a subscriber
rospy.Subscriber('Number_Array', Int32MultiArray, callback)

#Keep the script running
rospy.spin()

if __name__ == '__main__':
try:
number_array_subscriber()
except rospy.ROSInterruptException:
pass
